version: '3'
networks:
  lan:

services:
  application:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    command:
      - /docker-entrypoint-init.d/init.sh
    networks: 
      - lan
    ports:
      - 80:80
    restart: "no"
    environment:
      APP_ENV: local
    volumes:
      - ./composer_cache:/root/.composer/cache
      - ./www:/var/www
      - ./docker/scripts/init.sh:/docker-entrypoint-init.d/init.sh
      - ./:/var/www/host
    depends_on: 
      - db

  db:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysqlPassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: mysqlPassword
      MYSQL_ROOT_HOST: '%'
    image: mysql
    networks: 
      - lan
    ports:
      - 3306:3306
    restart: "no"
    volumes:
      - ./db_data:/var/lib/mysql
