version: '3'
#volumes:
#  db_data:

services:
  db:
    image: akoller/low-memory-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: mysqlPassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: mysqlPassword
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      # Volume dos dados
#      - db_data:/var/lib/mysql/
      - ./db_data:/var/lib/mysql
